# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EatGlasgowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (0, 'Deleted'), (-1, 'Closed')], default=1),
        ),
    ]
