# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EatGlasgowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOwner', models.IntegerField(choices=[(1, 'isOwner'), (0, 'isLocked')], default=1)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EatGlasgowApp.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('resID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='restaurant_images')),
                ('cuisine', models.CharField(choices=[('WE', 'Western'), ('AS', 'Asian'), ('ME', 'Middle Eastern')], max_length=2)),
                ('streetAddress', models.CharField(blank=True, max_length=100)),
                ('priceRange', models.IntegerField(choices=[(0, 'Not Rated'), (1, 'Low Price'), (2, 'Affordable'), (3, 'Fancy')], default=0)),
                ('openingHour', models.CharField(blank=True, max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Stored'), (0, 'Deleted'), (-1, 'Closed')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EatGlasgowApp.Owner')),
            ],
        ),
    ]
