# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:06
from __future__ import unicode_literals

import EatGlasgowApp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EatGlasgowApp', '0002_owner_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotionID', models.AutoField(primary_key=True, serialize=False)),
                ('fromDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('toDate', models.DateTimeField(default=EatGlasgowApp.models.one_week_hence)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Activating'), (0, 'Deleted'), (-1, 'Expired')], default=1)),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EatGlasgowApp.Restaurant')),
            ],
        ),
    ]
