# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EatGlasgowApp', '0003_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('repID', models.AutoField(primary_key=True, serialize=False)),
                ('repDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content', models.CharField(max_length=200)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('revID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='review_images')),
                ('rating', models.IntegerField(choices=[(0, 'Not Rated'), (1, 'Poor'), (2, 'Okay'), (3, 'Excellent')], default=0)),
                ('status', models.IntegerField(choices=[(1, 'Stored'), (0, 'Deleted')], default=1)),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EatGlasgowApp.Restaurant')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='revID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EatGlasgowApp.Review'),
        ),
    ]
